name: ðŸ”¥ Worker Sentinel ULTIMATE

on:
  repository_dispatch:
    types: [scan_target]
  workflow_dispatch:
    inputs:
      target:
        description: 'Target domain'
        required: true
        type: string
      intensity:
        description: 'Scan intensity (1-3)'
        required: false
        default: '2'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
      enable_ai:
        description: 'Enable AI Analysis'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      notification_mode:
        description: 'Notification mode'
        required: false
        default: 'vulnerabilities_only'
        type: choice
        options:
          - 'all'
          - 'vulnerabilities_only'
          - 'critical_only'

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
      - name: ðŸŽ¯ Get Target
        id: target
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            TARGET="${{ github.event.client_payload.target }}"
            INTENSITY="${{ github.event.client_payload.intensity }}"
            ENABLE_AI="${{ github.event.client_payload.enable_ai }}"
            NOTIFICATION_MODE="${{ github.event.client_payload.notification_mode }}"
          else
            TARGET="${{ github.event.inputs.target }}"
            INTENSITY="${{ github.event.inputs.intensity }}"
            ENABLE_AI="${{ github.event.inputs.enable_ai }}"
            NOTIFICATION_MODE="${{ github.event.inputs.notification_mode }}"
          fi
          
          TARGET=$(echo "$TARGET" | sed 's/https\?:\/\///' | sed 's/\/.*//')
          
          echo "target=$TARGET" >> $GITHUB_OUTPUT
          echo "intensity=${INTENSITY:-2}" >> $GITHUB_OUTPUT
          echo "enable_ai=${ENABLE_AI:-true}" >> $GITHUB_OUTPUT
          echo "notification_mode=${NOTIFICATION_MODE:-vulnerabilities_only}" >> $GITHUB_OUTPUT
          echo "scan_id=$(date +%s)" >> $GITHUB_OUTPUT
          
          echo "ðŸŽ¯ Target: $TARGET"
          echo "âš¡ Intensity: ${INTENSITY:-2}"
          echo "ðŸ¤– AI: ${ENABLE_AI:-true}"
          echo "ðŸ”” Mode: ${NOTIFICATION_MODE:-vulnerabilities_only}"
      
      - name: ðŸ”§ Install Tools
        run: |
          echo "ðŸ“¦ Installing security tools..."
          
          # Subfinder
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          
          # HTTPX
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          
          # Katana
          go install -v github.com/projectdiscovery/katana/cmd/katana@latest
          
          # Nuclei
          go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          
          # Add to PATH
          echo "$HOME/go/bin" >> $GITHUB_PATH
          
          echo "âœ… Tools installed"
      
      - name: ðŸ” Subdomain Discovery
        id: subdomains
        run: |
          TARGET="${{ steps.target.outputs.target }}"
          INTENSITY="${{ steps.target.outputs.intensity }}"
          
          echo "ðŸ” Discovering subdomains for $TARGET..."
          
          # Configure timeout based on intensity
          if [ "$INTENSITY" -ge "3" ]; then
            TIMEOUT=10
          elif [ "$INTENSITY" -ge "2" ]; then
            TIMEOUT=5
          else
            TIMEOUT=3
          fi
          
          # Run subfinder
          subfinder -d "$TARGET" -silent -timeout $TIMEOUT -o subs.txt 2>/dev/null || touch subs.txt
          
          # Fallback if no subdomains found
          if [ ! -s subs.txt ]; then
            echo "âš ï¸ No subdomains found, using target itself"
            echo "$TARGET" > subs.txt
            echo "www.$TARGET" >> subs.txt
            echo "api.$TARGET" >> subs.txt
            echo "mail.$TARGET" >> subs.txt
            echo "dev.$TARGET" >> subs.txt
            echo "staging.$TARGET" >> subs.txt
            echo "admin.$TARGET" >> subs.txt
          fi
          
          # Clean and deduplicate
          sort -u subs.txt -o subs.txt
          
          COUNT=$(wc -l < subs.txt)
          echo "âœ… Subdomains found: $COUNT"
          echo "count=$COUNT" >> $GITHUB_OUTPUT
          
          head -20 subs.txt
      
      - name: ðŸŒ HTTP Probing
        id: http
        run: |
          INTENSITY="${{ steps.target.outputs.intensity }}"
          
          echo "ðŸŒ Probing HTTP services..."
          
          # Configure threads based on intensity
          if [ "$INTENSITY" -ge "3" ]; then
            THREADS=50
            TIMEOUT=15
          elif [ "$INTENSITY" -ge "2" ]; then
            THREADS=30
            TIMEOUT=10
          else
            THREADS=20
            TIMEOUT=5
          fi
          
          # Run httpx
          cat subs.txt | httpx -silent -threads $THREADS -timeout $TIMEOUT \
            -follow-redirects -status-code -title -tech-detect \
            -o live.txt 2>/dev/null || touch live.txt
          
          # Fallback if no live hosts
          if [ ! -s live.txt ]; then
            TARGET="${{ steps.target.outputs.target }}"
            echo "âš ï¸ No live hosts found, trying direct URLs"
            echo "http://$TARGET" > live.txt
            echo "https://$TARGET" >> live.txt
          fi
          
          # Clean URLs
          sed -i 's/ .*//' live.txt
          sort -u live.txt -o live.txt
          
          COUNT=$(wc -l < live.txt)
          echo "âœ… Live hosts: $COUNT"
          echo "count=$COUNT" >> $GITHUB_OUTPUT
          
          head -20 live.txt
      
      - name: ðŸ•·ï¸ Web Crawling
        id: crawl
        run: |
          INTENSITY="${{ steps.target.outputs.intensity }}"
          
          echo "ðŸ•·ï¸ Crawling for URLs..."
          
          # Configure depth based on intensity
          if [ "$INTENSITY" -ge "3" ]; then
            DEPTH=3
            MAX_PAGES=500
          elif [ "$INTENSITY" -ge "2" ]; then
            DEPTH=2
            MAX_PAGES=200
          else
            DEPTH=1
            MAX_PAGES=50
          fi
          
          # Run katana (limit to first 5 hosts to avoid timeout)
          cat live.txt | head -5 | katana -silent -depth $DEPTH \
            -js-crawl -timeout 10 -o urls.txt 2>/dev/null || cp live.txt urls.txt
          
          # Combine with live hosts
          cat live.txt >> urls.txt
          sort -u urls.txt -o urls.txt
          
          COUNT=$(wc -l < urls.txt)
          echo "âœ… URLs discovered: $COUNT"
          echo "count=$COUNT" >> $GITHUB_OUTPUT
          
          head -20 urls.txt
      
      - name: ðŸ”Ž Nuclei Vulnerability Scan
        id: nuclei
        run: |
          INTENSITY="${{ steps.target.outputs.intensity }}"
          
          echo "ðŸ”Ž Scanning for vulnerabilities..."
          
          # Update templates
          nuclei -update-templates -silent 2>/dev/null || true
          
          # Configure severity and rate limit based on intensity
          if [ "$INTENSITY" -ge "3" ]; then
            SEV="critical,high,medium,low,info"
            RATE=150
          elif [ "$INTENSITY" -ge "2" ]; then
            SEV="critical,high,medium"
            RATE=100
          else
            SEV="critical,high"
            RATE=50
          fi
          
          # Run nuclei
          cat live.txt | nuclei -silent -severity $SEV -timeout 15 \
            -rate-limit $RATE -json -o nuclei.json 2>/dev/null || touch nuclei.json
          
          cat live.txt | nuclei -silent -severity $SEV -timeout 15 \
            -rate-limit $RATE -o results.txt 2>/dev/null || touch results.txt
          
          # Count vulnerabilities
          if [ -s nuclei.json ]; then
            COUNT=$(wc -l < nuclei.json)
          else
            COUNT=0
          fi
          
          echo "âœ… Vulnerabilities found: $COUNT"
          echo "count=$COUNT" >> $GITHUB_OUTPUT
          
          if [ "$COUNT" -gt "0" ]; then
            echo "ðŸ“‹ Sample findings:"
            head -5 results.txt
          fi
      
      - name: ðŸ¤– AI Analysis & Discord Reporting
        run: |
          TARGET="${{ steps.target.outputs.target }}"
          SUBS="${{ steps.subdomains.outputs.count }}"
          LIVE="${{ steps.http.outputs.count }}"
          URLS="${{ steps.crawl.outputs.count }}"
          VULN="${{ steps.nuclei.outputs.count }}"
          ENABLE_AI="${{ steps.target.outputs.enable_ai }}"
          NOTIFICATION_MODE="${{ steps.target.outputs.notification_mode }}"
          SCAN_ID="${{ steps.target.outputs.scan_id }}"
          
          # Determine if we should send notification
          SHOULD_NOTIFY=false
          
          if [ "$NOTIFICATION_MODE" = "all" ]; then
            SHOULD_NOTIFY=true
          elif [ "$NOTIFICATION_MODE" = "critical_only" ] && [ "$VULN" -gt "0" ]; then
            # Check if there are critical/high vulns
            if grep -q '"severity":"critical"\|"severity":"high"' nuclei.json 2>/dev/null; then
              SHOULD_NOTIFY=true
            fi
          elif [ "$NOTIFICATION_MODE" = "vulnerabilities_only" ] && [ "$VULN" -gt "0" ]; then
            SHOULD_NOTIFY=true
          fi
          
          if [ "$SHOULD_NOTIFY" = "true" ]; then
            echo "ðŸ“¤ Sending Discord notification..."
            
            # Determine color based on vulnerabilities
            if [ "$VULN" -gt "0" ]; then
              COLOR=15158332  # Red
              TITLE="ðŸš¨ Vulnerabilities Found!"
            else
              COLOR=5763719   # Green
              TITLE="âœ… Scan Complete - No Vulnerabilities"
            fi
            
            # Send summary
            curl -H "Content-Type: application/json" \
                 -d '{
                   "embeds": [{
                     "title": "'"$TITLE"'",
                     "description": "**Target:** '"$TARGET"'\n**Scan ID:** '"$SCAN_ID"'",
                     "color": '"$COLOR"',
                     "fields": [
                       {"name": "ðŸ” Subdomains", "value": "'"$SUBS"'", "inline": true},
                       {"name": "ðŸŒ Live Hosts", "value": "'"$LIVE"'", "inline": true},
                       {"name": "ðŸ•·ï¸ URLs", "value": "'"$URLS"'", "inline": true},
                       {"name": "ðŸ› Vulnerabilities", "value": "'"$VULN"'", "inline": true}
                     ],
                     "footer": {"text": "Digital Sentinel ULTIMATE"},
                     "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"
                   }]
                 }' \
                 ${{ secrets.DISCORD_WEBHOOK_URL }} 2>/dev/null || true
            
            sleep 2
            
            # Send detailed vulnerability reports
            if [ "$VULN" -gt "0" ] && [ -s nuclei.json ]; then
              echo "ðŸ“‹ Sending detailed vulnerability reports..."
              
              while IFS= read -r line; do
                # Parse JSON
                VULN_NAME=$(echo "$line" | grep -o '"template-id":"[^"]*"' | cut -d'"' -f4 || echo "Unknown")
                VULN_TYPE=$(echo "$line" | grep -o '"type":"[^"]*"' | cut -d'"' -f4 || echo "Unknown")
                SEVERITY=$(echo "$line" | grep -o '"severity":"[^"]*"' | cut -d'"' -f4 || echo "info")
                MATCHED_AT=$(echo "$line" | grep -o '"matched-at":"[^"]*"' | cut -d'"' -f4 || echo "Unknown")
                DESCRIPTION=$(echo "$line" | grep -o '"description":"[^"]*"' | cut -d'"' -f4 || echo "No description")
                
                # Severity color
                case "$SEVERITY" in
                  critical) SEV_COLOR=10038562 ;;
                  high) SEV_COLOR=15158332 ;;
                  medium) SEV_COLOR=16098851 ;;
                  low) SEV_COLOR=16776960 ;;
                  *) SEV_COLOR=9807270 ;;
                esac
                
                # AI Analysis
                AI_ANALYSIS=""
                if [ "$ENABLE_AI" = "true" ] && [ -n "${{ secrets.GEMINI_API_KEY }}" ]; then
                  echo "ðŸ¤– Running AI analysis for $VULN_NAME..."
                  
                  AI_PROMPT="You are a senior security researcher. Analyze this vulnerability briefly (max 200 words):

Vulnerability: $VULN_NAME
Type: $VULN_TYPE
Severity: $SEVERITY
URL: $MATCHED_AT

Provide:
1. Impact (2-3 sentences)
2. Exploitation difficulty (Easy/Medium/Hard)
3. Bug bounty value estimate
4. Key recommendation

Be concise and actionable."
                  
                  AI_RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${{ secrets.GEMINI_API_KEY }}" \
                    -H "Content-Type: application/json" \
                    -d '{
                      "contents": [{
                        "parts": [{"text": "'"${AI_PROMPT}"'"}]
                      }],
                      "generationConfig": {
                        "temperature": 0.7,
                        "maxOutputTokens": 500
                      }
                    }' 2>/dev/null | grep -o '"text":"[^"]*"' | head -1 | cut -d'"' -f4 || echo "")
                  
                  if [ -n "$AI_RESPONSE" ]; then
                    AI_ANALYSIS="\n\n**ðŸ¤– AI Security Analysis:**\n$AI_RESPONSE"
                  fi
                fi
                
                # Send detailed report
                curl -H "Content-Type: application/json" \
                     -d '{
                       "embeds": [{
                         "title": "ðŸ› '"$VULN_NAME"'",
                         "description": "**Type:** '"$VULN_TYPE"'\n**Severity:** '"${SEVERITY^^}"'\n**URL:** '"$MATCHED_AT"'\n\n**Description:**\n'"$DESCRIPTION"''"$AI_ANALYSIS"'",
                         "color": '"$SEV_COLOR"',
                         "fields": [
                           {"name": "ðŸŽ¯ Target", "value": "'"$TARGET"'", "inline": true},
                           {"name": "ðŸ”¥ Severity", "value": "'"${SEVERITY^^}"'", "inline": true},
                           {"name": "ðŸ“… Discovered", "value": "'"$(date +%Y-%m-%d)"'", "inline": true}
                         ],
                         "footer": {"text": "Scan ID: '"$SCAN_ID"' | Ready for Bug Bounty Submission"},
                         "timestamp": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"
                       }]
                     }' \
                     ${{ secrets.DISCORD_WEBHOOK_URL }} 2>/dev/null || true
                
                sleep 2
              done < nuclei.json
            fi
          else
            echo "âœ… No notification sent (mode: $NOTIFICATION_MODE, vulns: $VULN)"
          fi
      
      - name: ðŸ“Š Summary
        run: |
          TARGET="${{ steps.target.outputs.target }}"
          SUBS="${{ steps.subdomains.outputs.count }}"
          LIVE="${{ steps.http.outputs.count }}"
          URLS="${{ steps.crawl.outputs.count }}"
          VULN="${{ steps.nuclei.outputs.count }}"
          ENABLE_AI="${{ steps.target.outputs.enable_ai }}"
          NOTIFICATION_MODE="${{ steps.target.outputs.notification_mode }}"
          
          echo "## ðŸ”¥ Scan Complete: $TARGET" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ðŸ“Š Results:" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸ” **Subdomains:** $SUBS" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸŒ **Live Hosts:** $LIVE" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸ•·ï¸ **URLs Discovered:** $URLS" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸ› **Vulnerabilities:** $VULN" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### âš™ï¸ Configuration:" >> $GITHUB_STEP_SUMMARY
          echo "- âš¡ **Intensity:** ${{ steps.target.outputs.intensity }}" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸ¤– **AI Analysis:** $ENABLE_AI" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸ”” **Notification Mode:** $NOTIFICATION_MODE" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "$VULN" -gt "0" ]; then
            echo "### ðŸš¨ Vulnerabilities Detected!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Detailed reports have been sent to Discord.**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
            echo "1. Review findings in Discord" >> $GITHUB_STEP_SUMMARY
            echo "2. Verify vulnerabilities manually" >> $GITHUB_STEP_SUMMARY
            echo "3. Prepare bug bounty report" >> $GITHUB_STEP_SUMMARY
            echo "4. Submit to appropriate platform" >> $GITHUB_STEP_SUMMARY
          else
            echo "### âœ… No Vulnerabilities Found" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The target appears to be secure against common vulnerabilities." >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: ðŸ“¦ Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scan-results-${{ steps.target.outputs.target }}-${{ steps.target.outputs.scan_id }}
          path: |
            subs.txt
            live.txt
            urls.txt
            nuclei.json
            results.txt
          retention-days: 90
